## Climate Action Tracker - Country Assessments 


The Climate Action Tracker develops national greenhouse gas emission scenarios to assess countries' mitigation efforts. 
These scenarios include both pledges, such as NDCs and net zero commitments, and emission trajectories under currently adopted policies and actions.
For more details please visit the methodology section on our website: https://climateactiontracker.org/methodology/estimating-national-emissions/

Here, we present the latest version of the scenarios developed for each country. Please note that the assessment date varies per country and that some updates from the past month may not yet be reflected in this table.

Values in the table below are in MtCO2e/year and AR4 GWPs.

Please reference as: 'Climate Action Tracker, Country Assessments | November 2024 - http://climateactiontracker.org'

Copyright © 2024 Climate Action Tracker by NewClimate Institute and Climate Analytics. All rights reserved. The content provided by this website is protected by copyright. 
You are authorised to view, download, print and distribute the content from this website subject to the following condition: Any reproduction, in full or in part, must credit Climate Analytics and NewClimate Institute and must include a copyright notice.

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
url='https://climateactiontracker.org/documents/1289/CAT_14112024_CountryAssessmentData_DataExplorer.xlsx'

In [3]:
file_path = 'CAT_14112024_CountryAssessmentData_DataExplorer.xlsx'
sheet_name = 'Assessment'

In [4]:
# Reload the data with the first row as headers using openpyxl engine
emissions = pd.read_excel(url, sheet_name=sheet_name, skiprows=18, engine='openpyxl')
emissions

,Unnamed: 0,Unnamed: 1,Version,Country,Scenario,Sector,Indicator,Unit,1990,1991,...,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
0,NaN,NaN,112023,ARE,"Current Policy, Max","Economy-wide, excluding LULUCF",Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,274.530000,282.050000,289.610000,297.190000,304.260000,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,112023,ARE,"Current Policy, Min","Economy-wide, excluding LULUCF",Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,268.510000,275.120000,281.790000,288.510000,294.030000,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,112023,ARE,Historical,"Economy-wide, excluding LULUCF",Emissions (absolute),MtCO2e (GWP-AR4),61.7,67.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,112023,ARE,Historical,LULUCF,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,112023,ARE,"NDC Unconditional, Max","Economy-wide, excluding LULUCF",Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,206.200000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,NaN,NaN,32024,ZAF,Critically insufficient,"Economy-wide, excluding LULUCF",Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,608.381753,644.383495,680.385237,716.386979,752.388721,764.743580,777.098439,789.453298,801.808158,814.163017
823,NaN,NaN,32024,ZAF,Highly insufficient,"Economy-wide, excluding LULUCF",Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,552.122875,559.728981,567.335088,574.941194,582.547301,591.603831,600.660361,609.716891,618.773421,627.829951
824,NaN,NaN,32024,ZAF,Insufficient,"Economy-wide, excluding LULUCF",Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,494.314312,492.322624,490.330935,488.339247,486.347558,484.276181,482.204803,480.133425,478.062047,475.990669
825,NaN,NaN,32024,ZAF,Lower limit,"Economy-wide, excluding LULUCF",Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,237.075009,215.609765,194.144520,172.679276,151.214032,139.659994,128.105956,116.551918,104.997880,93.443842
826,NaN,NaN,32024,ZAF,Upper limit,"Economy-wide, excluding LULUCF",Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,714.023897,752.745054,791.466212,830.187369,868.908526,894.921123,920.933720,946.946317,972.958914,998.971511

LULUCF stands for Land Use, Land-Use Change, and Forestry. In emissions tracking, it refers to the greenhouse gas (GHG) emissions and removals resulting from human activities in forests, croplands, grasslands, wetlands, and other land-use types.

LULUCF plays a dual role in emissions accounting:

Source of Emissions: When forests are cleared, burned, or degraded, or when land is converted to agricultural or other uses, it releases stored carbon into the atmosphere.

Carbon Sink: LULUCF activities can also act as a carbon sink by removing CO₂ from the atmosphere, for example, through reforestation, afforestation, or improved land management practices.

In climate agreements and national emissions inventories, LULUCF is often included separately due to its unique nature of both emitting and absorbing

In [5]:
emissions_cleaned = emissions.dropna(subset=["Country"])
emissions_cleaned
# i want to replace the value in the column "Sector" with "Emissions-exLU" where the value is "Economy-wide, excluding LULUCF"
emissions_cleaned['Sector'] = emissions_cleaned['Sector'].replace("Economy-wide, excluding LULUCF", "Emissions-exLU")
#emissions_cleaned.loc[emissions_cleaned['Sector'] == "Economy-wide, excluding LULUCF", 'Sector'] = "Emissions-exLU"

emissions_cleaned

,Unnamed: 0,Unnamed: 1,Version,Country,Scenario,Sector,Indicator,Unit,1990,1991,...,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
0,NaN,NaN,112023,ARE,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,274.530000,282.050000,289.610000,297.190000,304.260000,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,112023,ARE,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,268.510000,275.120000,281.790000,288.510000,294.030000,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,112023,ARE,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),61.7,67.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,112023,ARE,Historical,LULUCF,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,112023,ARE,"NDC Unconditional, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,206.200000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,NaN,NaN,32024,ZAF,Critically insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,608.381753,644.383495,680.385237,716.386979,752.388721,764.743580,777.098439,789.453298,801.808158,814.163017
823,NaN,NaN,32024,ZAF,Highly insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,552.122875,559.728981,567.335088,574.941194,582.547301,591.603831,600.660361,609.716891,618.773421,627.829951
824,NaN,NaN,32024,ZAF,Insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,494.314312,492.322624,490.330935,488.339247,486.347558,484.276181,482.204803,480.133425,478.062047,475.990669
825,NaN,NaN,32024,ZAF,Lower limit,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,237.075009,215.609765,194.144520,172.679276,151.214032,139.659994,128.105956,116.551918,104.997880,93.443842
826,NaN,NaN,32024,ZAF,Upper limit,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,714.023897,752.745054,791.466212,830.187369,868.908526,894.921123,920.933720,946.946317,972.958914,998.971511

In [6]:
# lets look at China
china = emissions_cleaned[emissions_cleaned['Country'] == 'CHN']
china

,Unnamed: 0,Unnamed: 1,Version,Country,Scenario,Sector,Indicator,Unit,1990,1991,...,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
160,NaN,NaN,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,14859.72,14790.80,14721.87,14652.95,14568.40,14253.28,13938.16,13623.04,13307.92,12992.81
161,NaN,NaN,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,14307.17,14189.10,14071.03,13952.96,13819.27,13514.53,13209.79,12905.05,12600.31,12295.57
162,NaN,NaN,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),3635.8,3780.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,NaN,NaN,92024,CHN,Historical,LULUCF,Emissions (absolute),MtCO2e (GWP-AR4),-407.0,-407.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,NaN,NaN,92024,CHN,"NDC Unconditional, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,14568.40,NaN,NaN,NaN,NaN,NaN
165,NaN,NaN,92024,CHN,"NDC Unconditional, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,13512.36,NaN,NaN,NaN,NaN,NaN
166,NaN,NaN,92024,CHN,1.5C compatible,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,8736.03,NaN,NaN,NaN,NaN,NaN
167,NaN,NaN,92024,CHN,Almost sufficient,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,11211.73,NaN,NaN,NaN,NaN,NaN
168,NaN,NaN,92024,CHN,Highly insufficient,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,21108.66,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,92024,CHN,Insufficient,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,16158.27,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,92024,CHN,Lower limit,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,3944.46,NaN,NaN,NaN,NaN,NaN
171,NaN,NaN,92024,CHN,Upper limit,Emissions-exLU,Equity boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,NaN,NaN,NaN,NaN,15941.22,NaN,NaN,NaN,NaN,NaN
172,NaN,NaN,32024,CHN,1.5C compatible,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,8834.04,8334.75,7835.46,7336.17,6836.88,6508.95,6181.01,5853.08,5525.15,5197.21
173,NaN,NaN,32024,CHN,Almost sufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,11305.54,10883.39,10461.23,10039.07,9616.91,9125.52,8634.12,8142.73,7651.33,7159.93
174,NaN,NaN,32024,CHN,Critically insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,15938.79,16330.52,16722.25,17113.97,17505.70,17829.89,18154.07,18478.25,18802.44,19126.62
175,NaN,NaN,32024,CHN,Highly insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,14363.54,14415.22,14466.89,14518.57,14570.25,14474.28,14378.32,14282.35,14186.38,14090.41
176,NaN,NaN,32024,CHN,Insufficient,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,12900.98,12735.42,12569.87,12404.31,12238.75,12063.29,11887.83,11712.37,11536.91,11361.45
177,NaN,NaN,32024,CHN,Lower limit,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,7067.76,6521.30,5974.84,5428.38,4881.92,4697.36,4512.80,4328.24,4143.68,3959.12
178,NaN,NaN,32024,CHN,Upper limit,Emissions-exLU,Modelled Domestic Pathways boundaries (absolute),MtCO2e (GWP-AR4),NaN,NaN,...,17485.14,17980.92,18476.71,18972.50,19468.29,19985.64,20502.99,21020.34,21537.69,22055.04

### Lets looks at China Historical Emissions

Scenario = "Historical" and sector = "Emissions-exLU"

In [7]:
china_historical = china[(china['Scenario'] == 'Historical') & (china['Sector'] == 'Emissions-exLU')]
china_historical

,Unnamed: 0,Unnamed: 1,Version,Country,Scenario,Sector,Indicator,Unit,1990,1991,...,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
162,NaN,NaN,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),3635.8,3780.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###  The data are in the wrong shape for analysis.
- The years are spread out as columns
- Let's  `melt` the DataFrame so that years become rows under a 'Year' column

In [8]:
china_historical_melted = pd.melt(
    china_historical, 
    id_vars=['Version', 'Country', 'Scenario', 'Sector', 'Indicator', 'Unit'],  
    var_name='Year',
    value_name='Emissions'  
)

china_historical_melted['Year'] = pd.to_numeric(china_historical_melted['Year'], errors='coerce')

china_historical_melted.head()

,Version,Country,Scenario,Sector,Indicator,Unit,Year,Emissions
0,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN
1,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),NaN,NaN
2,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),1990.0,3635.8
3,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),1991.0,3780.5
4,92024,CHN,Historical,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),1992.0,3906.4

In [9]:
fig = px.line(china_historical_melted, x='Year', y='Emissions', title='China Emissions-exLU Historical')
fig.show()

##  Now let's get the Forecast data 

In this dataset these are called "current policy scenario,max" and "current policy scenario,min".  
- We will use the same process 'melt' as above to get the data in the right shape for analysis.

In [10]:
china_current_policy = china[china['Scenario'].str.contains('Current Policy')]

china_current_policy_melted = pd.melt(
    china_current_policy, 
    id_vars=['Version', 'Country', 'Scenario', 'Sector', 'Indicator', 'Unit'], 
    var_name='Year',  
    value_name='Emissions' 
)

china_current_policy_melted

,Version,Country,Scenario,Sector,Indicator,Unit,Year,Emissions
0,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),Unnamed: 0,NaN
1,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),Unnamed: 0,NaN
2,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),Unnamed: 1,NaN
3,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),Unnamed: 1,NaN
4,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),1990,NaN
...,...,...,...,...,...,...,...,...
91,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2033,12905.05
92,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2034,13307.92
93,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2034,12600.31
94,92024,CHN,"Current Policy, Max",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2035,12992.81
95,92024,CHN,"Current Policy, Min",Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2035,12295.57

Now we need to pivot the data so that we have the following columns:
- Year
- Max Emissions
- Min Emissions

In [11]:
data_melted = china_current_policy_melted
china_current_policy_melted['Year'] = pd.to_numeric(china_current_policy_melted['Year'], errors='coerce')

china_forecast_pivot = china_current_policy_melted.pivot_table(
    index=['Version', 'Country', 'Sector', 'Indicator', 'Unit', 'Year'],  
    columns='Scenario',  
    values='Emissions'  
).reset_index()  

# Rename the columns for clarity
china_forecast_pivot.columns.name = None  
china_forecast_pivot.rename(columns={'Current Policy, Max': 'Max_Forecast', 'Current Policy, Min': 'Min_Forecast'}, inplace=True)

china_forecast_pivot

,Version,Country,Sector,Indicator,Unit,Year,Max_Forecast,Min_Forecast
0,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2022.0,14463.60,14463.60
1,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2023.0,14911.25,14911.25
2,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2024.0,14913.34,14661.64
3,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2025.0,14928.65,14425.24
4,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2026.0,14859.72,14307.17
5,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2027.0,14790.80,14189.10
6,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2028.0,14721.87,14071.03
7,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2029.0,14652.95,13952.96
8,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2030.0,14568.40,13819.27
9,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2031.0,14253.28,13514.53
10,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2032.0,13938.16,13209.79
11,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2033.0,13623.04,12905.05
12,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2034.0,13307.92,12600.31
13,92024,CHN,Emissions-exLU,Emissions (absolute),MtCO2e (GWP-AR4),2035.0,12992.81,12295.57

Let's plot the data to see the trends in the emissions

In [12]:
fig = px.line(china_forecast_pivot, x='Year', y='Max_Forecast', title='China Emissions-exLU Current Policy')
fig.add_scatter(x=china_forecast_pivot['Year'], y=china_forecast_pivot['Min_Forecast'], mode='lines', name='Forecast Min')
fig.show()

Let's add historical data to the plot

In [13]:
fig = px.line(china_historical_melted, x='Year', y='Emissions', title='China Emissions-exLU Historical')
fig.add_scatter(x=china_forecast_pivot['Year'], y=china_forecast_pivot['Max_Forecast'], mode='lines', name='Max Emissions')
fig.add_scatter(x=china_forecast_pivot['Year'], y=china_forecast_pivot['Min_Forecast'], mode='lines', name='Min Emissions')
fig.show()